DROP TABLE IF EXISTS movies;

CREATE TABLE movies (
    id     SERIAL PRIMARY KEY,
    title  TEXT NOT NULL,
    year   INTEGER NOT NULL,
    rating NUMERIC(3,1) NOT NULL,
    genre  TEXT NOT NULL,
    actors TEXT[] NOT NULL
);

-- INSERT INTO movies (id, title, year, rating, genre, actors) VALUES
-- (1, 'The Shawshank Redemption', 1994, 9.3, 'Drama', ARRAY['Tim Robbins','Morgan Freeman','Bob Gunton']),
-- (2, 'The Godfather', 1972, 9.2, 'Crime', ARRAY['Marlon Brando','Al Pacino','James Caan']),
-- (3, 'The Dark Knight', 2008, 9.0, 'Action', ARRAY['Christian Bale','Heath Ledger','Aaron Eckhart']),
-- (4, 'Pulp Fiction', 1994, 8.9, 'Crime', ARRAY['John Travolta','Uma Thurman','Samuel L. Jackson']),
-- (5, 'Forrest Gump', 1994, 8.8, 'Drama', ARRAY['Tom Hanks','Robin Wright','Gary Sinise']),
-- (6, 'Inception', 2010, 8.8, 'Sci-Fi', ARRAY['Leonardo DiCaprio','Joseph Gordon-Levitt','Elliot Page']),
-- (7, 'The Matrix', 1999, 8.7, 'Sci-Fi', ARRAY['Keanu Reeves','Laurence Fishburne','Carrie-Anne Moss']),
-- (8, 'Goodfellas', 1990, 8.7, 'Crime', ARRAY['Robert De Niro','Ray Liotta','Joe Pesci']),
-- (9, 'Fight Club', 1999, 8.8, 'Drama', ARRAY['Brad Pitt','Edward Norton','Helena Bonham Carter']),
-- (10, 'Interstellar', 2014, 8.7, 'Sci-Fi', ARRAY['Matthew McConaughey','Anne Hathaway','Jessica Chastain']),
-- (11, 'The Silence of the Lambs', 1991, 8.6, 'Thriller', ARRAY['Jodie Foster','Anthony Hopkins','Scott Glenn']),
-- (12, 'Schindler''s List', 1993, 9.0, 'History', ARRAY['Liam Neeson','Ben Kingsley','Ralph Fiennes']),
-- (13, 'The Lord of the Rings', 2003, 9.0, 'Fantasy', ARRAY['Elijah Wood','Ian McKellen','Viggo Mortensen']),
-- (14, 'Star Wars: A New Hope', 1977, 8.6, 'Sci-Fi', ARRAY['Mark Hamill','Harrison Ford','Carrie Fisher']),
-- (15, 'Gladiator', 2000, 8.5, 'Action', ARRAY['Russell Crowe','Joaquin Phoenix','Connie Nielsen']),
-- (16, 'The Lion King', 1994, 8.5, 'Animation', ARRAY['Matthew Broderick','Jeremy Irons','James Earl Jones']),
-- (17, 'Avengers: Endgame', 2019, 8.4, 'Action', ARRAY['Robert Downey Jr.','Chris Evans','Mark Ruffalo']),
-- (18, 'Titanic', 1997, 7.9, 'Romance', ARRAY['Leonardo DiCaprio','Kate Winslet','Billy Zane']),
-- (19, 'Joker', 2019, 8.4, 'Drama', ARRAY['Joaquin Phoenix','Robert De Niro','Zazie Beetz']),
-- (20, 'Parasite', 2019, 8.5, 'Thriller', ARRAY['Song Kang-ho','Lee Sun-kyun','Cho Yeo-jeong']),
-- (21, 'Whiplash', 2014, 8.5, 'Drama', ARRAY['Miles Teller','J.K. Simmons','Melissa Benoist']),
-- (22, 'La La Land', 2016, 8.0, 'Romance', ARRAY['Ryan Gosling','Emma Stone','John Legend']),
-- (23, 'Get Out', 2017, 7.7, 'Horror', ARRAY['Daniel Kaluuya','Allison Williams','Bradley Whitford']),
-- (24, 'Black Panther', 2018, 7.3, 'Action', ARRAY['Chadwick Boseman','Michael B. Jordan','Lupita Nyong''o']),
-- (25, 'Spider-Man: Into the Spider-Verse', 2018, 8.4, 'Animation', ARRAY['Shameik Moore','Jake Johnson','Hailee Steinfeld']),
-- (26, '1917', 2019, 8.3, 'War', ARRAY['George MacKay','Dean-Charles Chapman','Mark Strong']),
-- (27, 'Baby Driver', 2017, 7.6, 'Action', ARRAY['Ansel Elgort','Jon Hamm','Jamie Foxx']),
-- (28, 'Mad Max: Fury Road', 2015, 8.1, 'Action', ARRAY['Tom Hardy','Charlize Theron','Nicholas Hoult']),
-- (29, 'The Revenant', 2015, 8.0, 'Adventure', ARRAY['Leonardo DiCaprio','Tom Hardy','Will Poulter']),
-- (30, 'Gone Girl', 2014, 8.1, 'Thriller', ARRAY['Ben Affleck','Rosamund Pike','Neil Patrick Harris']),
-- (31, 'Arrival', 2016, 7.9, 'Sci-Fi', ARRAY['Amy Adams','Jeremy Renner','Forest Whitaker']),
-- (32, 'Hereditary', 2018, 7.3, 'Horror', ARRAY['Toni Collette','Milly Shapiro','Gabriel Byrne']),
-- (33, 'Midsommar', 2019, 7.1, 'Horror', ARRAY['Florence Pugh','Jack Reynor','William Jackson Harper']),
-- (34, 'The Irishman', 2019, 7.8, 'Crime', ARRAY['Robert De Niro','Al Pacino','Joe Pesci']),
-- (35, 'Once Upon a Time in Hollywood', 2019, 7.6, 'Drama', ARRAY['Leonardo DiCaprio','Brad Pitt','Margot Robbie']),
-- (36, 'Knives Out', 2019, 7.9, 'Mystery', ARRAY['Daniel Craig','Chris Evans','Ana de Armas']),
-- (37, 'The Grand Budapest Hotel', 2014, 8.1, 'Comedy', ARRAY['Ralph Fiennes','Tony Revolori','Saoirse Ronan']),
-- (38, 'Dune', 2021, 8.0, 'Sci-Fi', ARRAY['Timothée Chalamet','Rebecca Ferguson','Oscar Isaac']),
-- (39, 'No Time to Die', 2021, 7.3, 'Action', ARRAY['Daniel Craig','Rami Malek','Léa Seydoux']),
-- (40, 'The Batman', 2022, 7.8, 'Action', ARRAY['Robert Pattinson','Zoë Kravitz','Paul Dano']),
-- (41, 'Everything Everywhere All at Once', 2022, 7.8, 'Sci-Fi', ARRAY['Michelle Yeoh','Ke Huy Quan','Jamie Lee Curtis']),
-- (42, 'Top Gun: Maverick', 2022, 8.3, 'Action', ARRAY['Tom Cruise','Miles Teller','Jennifer Connelly']),
-- (43, 'The Northman', 2022, 7.1, 'Adventure', ARRAY['Alexander Skarsgård','Nicole Kidman','Anya Taylor-Joy']),
-- (44, 'Nope', 2022, 6.9, 'Horror', ARRAY['Daniel Kaluuya','Keke Palmer','Steven Yeun']),
-- (45, 'Avatar', 2009, 7.9, 'Sci-Fi', ARRAY['Sam Worthington','Zoe Saldana','Sigourney Weaver']),
-- (46, 'Oppenheimer', 2023, 8.9, 'History', ARRAY['Cillian Murphy','Emily Blunt','Matt Damon']),
-- (47, 'Barbie', 2023, 7.0, 'Comedy', ARRAY['Margot Robbie','Ryan Gosling','America Ferrera']),
-- (48, 'John Wick', 2014, 7.4, 'Action', ARRAY['Keanu Reeves','Michael Nyqvist','Alfie Allen']),
-- (49, 'The Prestige', 2006, 8.5, 'Mystery', ARRAY['Christian Bale','Hugh Jackman','Scarlett Johansson']),
-- (50, 'Memento', 2000, 8.4, 'Mystery', ARRAY['Guy Pearce','Carrie-Anne Moss','Joe Pantoliano']);

SELECT setval('movies_id_seq', (SELECT MAX(id) FROM movies));